[package]
name = "common_traits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

half = {version="2.2.1", features=["use-intrinsics"], default-features = false, optional = true}

[features]
default = ["half", "std"]
atomic_from_mut = []
half = ["dep:half"]
simd = []
std = []